// Comprehensive question and flashcard bank (up to 50 items per pool)
// Grounded in Natural Resources, Solar Mission, Water Conflicts (Cauvery / Sardar Sarovar), and Fuel Cells

export const comprehensiveFlashcardsPool = [
  // 1-10: Solar & Renewable Energy (National Solar Mission)
  {
    id: 'fc-1',
    category: 'Solar & Renewable Energy',
    question: 'What is the theoretical efficiency equation for a hydrogen-oxygen fuel cell at 25°C?',
    answer: 'Theoretical Efficiency = (ΔG / ΔH) * 100 = (56.65 / 68.26) * 100 = 83%. Practical cells typically operate at 50–60% efficiency.',
  },
  {
    id: 'fc-2',
    category: 'Solar & Renewable Energy',
    question: 'What distinguish renewable from non-renewable natural resources?',
    answer: 'Renewables (solar, wind, biomass) replenish naturally at rates equal to or faster than consumption. Non-renewables (coal, petroleum) exist in finite geological reserves that deplete permanently upon extraction.',
  },
  {
    id: 'fc-3',
    category: 'Solar & Renewable Energy',
    question: 'What are the core targets of the Jawaharlal Nehru National Solar Mission (JNNSM)?',
    answer: 'Launched under NAPCC to establish India as a global solar hub, setting an ambitious revised target of 100 GW of solar capacity through utility parks and rooftop installations.',
  },
  {
    id: 'fc-4',
    category: 'Solar & Renewable Energy',
    question: 'What is the operational difference between Solar PV and Concentrated Solar Power (CSP)?',
    answer: 'Solar PV converts photons directly into DC electricity using semiconductor p-n junctions, whereas CSP uses mirrors to concentrate sunlight to heat a working fluid driving steam turbines.',
  },
  {
    id: 'fc-5',
    category: 'Solar & Renewable Energy',
    question: 'What is the typical composition of Biogas derived from anaerobic digestion?',
    answer: 'Biogas typically contains 55–65% Methane (CH4), 35–45% Carbon Dioxide (CO2), and traces of hydrogen sulfide (H2S) and moisture.',
  },
  {
    id: 'fc-6',
    category: 'Solar & Renewable Energy',
    question: 'What is the Levelized Cost of Electricity (LCOE)?',
    answer: 'LCOE is the net present value of total lifetime capital, operational, and maintenance costs divided by total lifetime electricity generated ($/MWh).',
  },
  {
    id: 'fc-7',
    category: 'Solar & Renewable Energy',
    question: 'How do solar microgrids enhance rural electrification resilience?',
    answer: 'By generating decentralized power near local demand loads with battery storage, avoiding transmission losses and vulnerable central grid dependencies.',
  },
  {
    id: 'fc-8',
    category: 'Solar & Renewable Energy',
    question: 'What semiconductor material currently dominates commercial photovoltaic cells?',
    answer: 'Crystalline silicon (c-Si), comprising monocrystalline and polycrystalline silicon wafers, accounting for >90% of global PV production.',
  },
  {
    id: 'fc-9',
    category: 'Solar & Renewable Energy',
    question: 'What is Net Metering in residential solar systems?',
    answer: 'A billing mechanism that credits solar PV owners for surplus electricity fed back into the public grid, offsetting subsequent grid consumption.',
  },
  {
    id: 'fc-10',
    category: 'Solar & Renewable Energy',
    question: 'What is the role of the International Solar Alliance (ISA)?',
    answer: 'A treaty-based intergovernmental coalition initiated by India and France to mobilize over $1 trillion in solar investment and foster clean energy access in sunshine nations.',
  },

  // 11-20: Water Resources & Hydrology
  {
    id: 'fc-11',
    category: 'Water Resources',
    question: 'What are the primary catastrophic consequences of groundwater over-exploitation?',
    answer: '1. Irreversible land subsidence, 2. Progressive lowering of water tables, 3. Coastal saltwater intrusion and aquifer salinization.',
  },
  {
    id: 'fc-12',
    category: 'Water Resources',
    question: 'What is an unconfined aquifer versus a confined (artesian) aquifer?',
    answer: 'An unconfined aquifer has a free water table at atmospheric pressure; a confined aquifer is trapped between impermeable geological aquitards under hydrostatic pressure.',
  },
  {
    id: 'fc-13',
    category: 'Water Resources',
    question: 'How does artificial rainwater harvesting support urban aquifer management?',
    answer: 'By capturing rooftop and surface runoff into recharge pits, filtering sediment, and replenishing depleted underground water tables.',
  },
  {
    id: 'fc-14',
    category: 'Water Resources',
    question: 'What causes secondary soil salinization in canal-irrigated command areas?',
    answer: 'Excessive irrigation and inadequate subsurface drainage cause the water table to rise near the root zone, evaporating water and precipitating dissolved salts.',
  },
  {
    id: 'fc-15',
    category: 'Water Resources',
    question: 'What is the difference between Blue Water, Green Water, and Grey Water?',
    answer: 'Blue Water is surface/groundwater; Green Water is soil moisture consumed by crops; Grey Water is wastewater generated from domestic sinks/showers without fecal contamination.',
  },
  {
    id: 'fc-16',
    category: 'Water Resources',
    question: 'What are check dams and how do they prevent gully erosion?',
    answer: 'Small barrier structures built across drainage ditches that reduce runoff flow velocity, trap fertile silt, and promote percolation.',
  },
  {
    id: 'fc-17',
    category: 'Water Resources',
    question: 'What is Virtual Water trade?',
    answer: 'The hidden volume of freshwater consumed throughout the manufacturing or agricultural cultivation of traded commodities and food products.',
  },
  {
    id: 'fc-18',
    category: 'Water Resources',
    question: 'What is water logging and its effect on plant respiration?',
    answer: 'Saturation of soil pores with stagnant water, displacing oxygen and causing anaerobic conditions that asphyxiate plant roots.',
  },
  {
    id: 'fc-19',
    category: 'Water Resources',
    question: 'What is reverse osmosis (RO) desalination and its environmental drawback?',
    answer: 'Pressurizing seawater across semipermeable membranes to extract drinking water; produces concentrated hyper-saline brine discharge harmful to marine life.',
  },
  {
    id: 'fc-20',
    category: 'Water Resources',
    question: 'What is the hydrological cycle primary driver?',
    answer: 'Solar radiation driving evaporation from oceans and evapotranspiration from vegetation into atmospheric vapor, leading to condensation and precipitation.',
  },

  // 21-30: Case Studies (Cauvery Conflict, Sardar Sarovar, Chipko)
  {
    id: 'fc-21',
    category: 'Case Studies',
    question: 'What is the fundamental dispute in the Cauvery River Water conflict?',
    answer: 'Equitable sharing of the Cauvery basin waters between upper-riparian Karnataka and lower-riparian Tamil Nadu, particularly during drought and deficit monsoon years.',
  },
  {
    id: 'fc-22',
    category: 'Case Studies',
    question: 'What are the main states involved in the Cauvery water allocation dispute?',
    answer: 'Karnataka, Tamil Nadu, Kerala, and the Union Territory of Puducherry, adjudicated by the Cauvery Water Disputes Tribunal (CWDT) and Supreme Court.',
  },
  {
    id: 'fc-23',
    category: 'Case Studies',
    question: 'Where is the Sardar Sarovar Dam built and what was its original dual purpose?',
    answer: 'Built on the Narmada River in Gujarat to provide irrigation water to arid regions of Gujarat/Rajasthan and generate 1,450 MW of hydroelectric power.',
  },
  {
    id: 'fc-24',
    category: 'Case Studies',
    question: 'What socio-environmental movement resisted the Sardar Sarovar Dam?',
    answer: 'The Narmada Bachao Andolan (NBA), led by Medha Patkar, protesting submergence of forests, loss of biodiversity, and displacement of indigenous tribal communities.',
  },
  {
    id: 'fc-25',
    category: 'Case Studies',
    question: 'What was the core method and aim of the Chipko Movement (1973)?',
    answer: 'Villagers (notably rural women) hugged forest trees in Uttarakhand to protect them from commercial logging and prevent Himalayan slope landslides.',
  },
  {
    id: 'fc-26',
    category: 'Case Studies',
    question: 'What was the Silent Valley Movement in Kerala about?',
    answer: 'A successful environmental campaign in the 1970s against a proposed hydroelectric project that would have submerged pristine tropical evergreen rainforests.',
  },
  {
    id: 'fc-27',
    category: 'Case Studies',
    question: 'What is the Helsinki Rules doctrine regarding transboundary waters?',
    answer: 'The principle of equitable and reasonable utilization of international and inter-state drainage basins considering geographic, hydrological, and demographic needs.',
  },
  {
    id: 'fc-28',
    category: 'Case Studies',
    question: 'What is the Mettur Dam role in the Cauvery river system?',
    answer: 'Located in Tamil Nadu, it acts as the primary reservoir for regulating irrigation discharge to the fertile Cauvery agricultural delta.',
  },
  {
    id: 'fc-29',
    category: 'Case Studies',
    question: 'What was the Appiko Movement in Karnataka inspired by?',
    answer: 'Inspired by the Himalayan Chipko Movement, southern villagers hugged trees in the Western Ghats to stop clear-felling and preserve tropical timber.',
  },
  {
    id: 'fc-30',
    category: 'Case Studies',
    question: 'How does the Cauvery Water Management Authority (CWMA) operate?',
    answer: 'It oversees periodic water releases from Karnataka reservoirs to the Biligundlu gauging station for downstream Tamil Nadu use based on real-time reservoir levels.',
  },

  // 31-40: Fuel Cells & Electrochemical Thermodynamics
  {
    id: 'fc-31',
    category: 'Fuel Cells',
    question: 'What is the operational difference between PEM and Solid Oxide fuel cells (SOFC)?',
    answer: 'PEM operates at low temperature (~80°C) with a polymer membrane for mobile uses; SOFC operates at high temperature (600–1000°C) using ceramic electrolytes for stationary grids.',
  },
  {
    id: 'fc-32',
    category: 'Fuel Cells',
    question: 'What reaction takes place at the anode of a PEM fuel cell?',
    answer: 'Hydrogen Oxidation Reaction (HOR): H2 -> 2H+ + 2e-, catalyzed typically by platinum nanoparticles.',
  },
  {
    id: 'fc-33',
    category: 'Fuel Cells',
    question: 'What reaction takes place at the cathode of a PEM fuel cell?',
    answer: 'Oxygen Reduction Reaction (ORR): 1/2 O2 + 2H+ + 2e- -> H2O, generating pure water and exothermic heat.',
  },
  {
    id: 'fc-34',
    category: 'Fuel Cells',
    question: 'Why do fuel cells exceed the theoretical Carnot efficiency limit?',
    answer: 'Because they convert Gibbs free energy (ΔG) directly into electrical work without passing through an intermediate thermal-mechanical cycle.',
  },
  {
    id: 'fc-35',
    category: 'Fuel Cells',
    question: 'What causes catalyst poisoning in low-temperature PEM fuel cells?',
    answer: 'Carbon monoxide (CO) trace impurities in reformed hydrogen adsorb tightly onto platinum catalyst active sites, blocking hydrogen dissociation.',
  },
  {
    id: 'fc-36',
    category: 'Fuel Cells',
    question: 'What polymer is standard for Proton Exchange Membranes?',
    answer: 'Nafion, a sulfonated tetrafluoroethylene copolymer exhibiting high proton conductivity when properly hydrated.',
  },
  {
    id: 'fc-37',
    category: 'Fuel Cells',
    question: 'What are the three main polarization loss regions in a fuel cell V-I curve?',
    answer: '1. Activation polarization (charge transfer resistance at low current), 2. Ohmic polarization (resistance of membrane and electrodes), 3. Concentration/mass transport polarization (reactant depletion at high current).',
  },
  {
    id: 'fc-38',
    category: 'Fuel Cells',
    question: 'What is Green Hydrogen versus Grey Hydrogen?',
    answer: 'Green Hydrogen is produced by water electrolysis powered by renewable electricity; Grey Hydrogen is derived from natural gas steam methane reforming releasing CO2.',
  },
  {
    id: 'fc-39',
    category: 'Fuel Cells',
    question: 'What is a Direct Methanol Fuel Cell (DMFC) advantage and drawback?',
    answer: 'Advantage: Liquid fuel is easy to transport. Drawback: Low efficiency due to methanol crossover across the polymer electrolyte membrane.',
  },
  {
    id: 'fc-40',
    category: 'Fuel Cells',
    question: 'What electrolyte is used in Alkaline Fuel Cells (AFC)?',
    answer: 'Aqueous potassium hydroxide (KOH), historically utilized in NASA Apollo and Space Shuttle missions.',
  },

  // 41-50: Land Resources & Environmental Policy
  {
    id: 'fc-41',
    category: 'Land & Environmental Policy',
    question: 'What are contour bunding and terracing in land conservation?',
    answer: 'Soil conservation practices where barriers or stepped benches are built across hill slope contours to slow runoff and retain topsoil.',
  },
  {
    id: 'fc-42',
    category: 'Land & Environmental Policy',
    question: 'What is desertification and what factors exacerbate it?',
    answer: 'Degradation of fertile dryland into arid desert caused by deforestation, overgrazing, intensive monoculture agriculture, and climate shifts.',
  },
  {
    id: 'fc-43',
    category: 'Land & Environmental Policy',
    question: 'What are the eight core national missions under India\'s NAPCC?',
    answer: 'Solar, Enhanced Energy Efficiency, Sustainable Habitat, Water, Himalayan Ecosystem, Green India, Sustainable Agriculture, and Strategic Knowledge for Climate Change.',
  },
  {
    id: 'fc-44',
    category: 'Land & Environmental Policy',
    question: 'What is sheet erosion versus gully erosion in soil science?',
    answer: 'Sheet erosion is the uniform removal of a thin topsoil layer by surface sheets of water; gully erosion occurs when runoff concentrates into deep carving channels.',
  },
  {
    id: 'fc-45',
    category: 'Land & Environmental Policy',
    question: 'What is Agroforestry and its ecological advantage?',
    answer: 'Integrating trees with agricultural crops and livestock on the same land parcel, enhancing biodiversity, microclimates, and carbon sequestration.',
  },
  {
    id: 'fc-46',
    category: 'Land & Environmental Policy',
    question: 'What is the Forest Conservation Act of 1980 in India?',
    answer: 'A landmark federal act requiring prior central government approval before any forest land is diverted or de-reserved for non-forest purposes.',
  },
  {
    id: 'fc-47',
    category: 'Land & Environmental Policy',
    question: 'What are shelterbelts and windbreaks?',
    answer: 'Linear rows of trees and shrubs planted perpendicular to prevailing winds to reduce wind velocity and protect dry topsoil from aeolian erosion.',
  },
  {
    id: 'fc-48',
    category: 'Land & Environmental Policy',
    question: 'What is the significance of the Ramsar Convention?',
    answer: 'An international treaty dedicated to the conservation and sustainable wise use of wetlands of global ecological importance.',
  },
  {
    id: 'fc-49',
    category: 'Land & Environmental Policy',
    question: 'What is Eutrophication and what natural resources does it threaten?',
    answer: 'Excessive nutrient runoff (nitrogen/phosphorus from fertilizer) fueling algal blooms that deplete dissolved oxygen, devastating freshwater lake and river ecosystems.',
  },
  {
    id: 'fc-50',
    category: 'Land & Environmental Policy',
    question: 'What is the Precautionary Principle in environmental jurisprudence?',
    answer: 'Where there are threats of serious or irreversible damage, lack of full scientific certainty shall not be used as a reason for postponing cost-effective measures to prevent environmental degradation.',
  },
];

export const comprehensiveMcqsPool = [
  // 1-10: Solar & Renewable Energy
  {
    id: 'mcq-1',
    category: 'Solar & Renewable Energy',
    question: 'Which national policy framework established the Jawaharlal Nehru National Solar Mission (JNNSM)?',
    options: ['National Clean Air Programme', 'National Action Plan on Climate Change (NAPCC)', 'Smart Cities Mission', 'National Water Mission'],
    correctIndex: 1,
    explanation: 'JNNSM is one of the eight core national missions launched under the NAPCC in 2010.',
  },
  {
    id: 'mcq-2',
    category: 'Solar & Renewable Energy',
    question: 'Which of the following is categorized as a non-renewable exhaustible resource?',
    options: ['Geothermal energy', 'Anthracite coal', 'Biomass briquettes', 'Tidal wave energy'],
    correctIndex: 1,
    explanation: 'Anthracite coal is a finite fossil fuel formed over geological epochs and cannot be replenished on human timescales.',
  },
  {
    id: 'mcq-3',
    category: 'Solar & Renewable Energy',
    question: 'What is the primary component of biogas produced from animal manure digestion?',
    options: ['Carbon Monoxide (CO)', 'Methane (CH4)', 'Hydrogen Sulfide (H2S)', 'Ethane (C2H6)'],
    correctIndex: 1,
    explanation: 'Biogas consists of approximately 55% to 65% Methane (CH4) alongside 35% to 45% Carbon Dioxide.',
  },
  {
    id: 'mcq-4',
    category: 'Solar & Renewable Energy',
    question: 'In photovoltaic cells, the bandgap energy of silicon is approximately:',
    options: ['0.2 eV', '1.1 eV', '3.5 eV', '6.0 eV'],
    correctIndex: 1,
    explanation: 'Crystalline silicon has an indirect bandgap of approximately 1.12 eV at room temperature.',
  },
  {
    id: 'mcq-5',
    category: 'Solar & Renewable Energy',
    question: 'Concentrating Solar Power (CSP) plants commonly use which medium for thermal energy storage?',
    options: ['Molten salts (nitrate mixtures)', 'Liquid ammonia', 'Compressed air', 'Gaseous nitrogen'],
    correctIndex: 0,
    explanation: 'Molten salt mixtures (sodium nitrate and potassium nitrate) store thermal energy up to 565°C for nighttime power generation.',
  },
  {
    id: 'mcq-6',
    category: 'Solar & Renewable Energy',
    question: 'Which country hosts the headquarters of the International Solar Alliance (ISA)?',
    options: ['France (Paris)', 'India (Gurugram)', 'Germany (Bonn)', 'Japan (Tokyo)'],
    correctIndex: 1,
    explanation: 'The ISA is headquartered at the National Institute of Solar Energy (NISE) in Gurugram, Haryana, India.',
  },
  {
    id: 'mcq-7',
    category: 'Solar & Renewable Energy',
    question: 'The photoelectric effect converts photon radiation directly into:',
    options: ['Thermal steam', 'Direct Current (DC) electricity', 'Alternating Current (AC) electricity', 'Mechanical torque'],
    correctIndex: 1,
    explanation: 'Photovoltaic cells release free charge carriers upon photon absorption, generating direct current (DC).',
  },
  {
    id: 'mcq-8',
    category: 'Solar & Renewable Energy',
    question: 'Which type of solar collector provides the highest concentration ratio?',
    options: ['Flat plate collector', 'Evacuated tube collector', 'Parabolic dish collector', 'Compound parabolic collector'],
    correctIndex: 2,
    explanation: 'Parabolic dish point-focus collectors achieve solar concentration ratios exceeding 1,000 to 3,000 suns.',
  },
  {
    id: 'mcq-9',
    category: 'Solar & Renewable Energy',
    question: 'The target solar power capacity under India\'s revised National Solar Mission was set to:',
    options: ['20 GW', '50 GW', '100 GW', '250 GW'],
    correctIndex: 2,
    explanation: 'The original 2022 target of 20 GW was scaled up five-fold to 100 GW under Prime Minister initiatives.',
  },
  {
    id: 'mcq-10',
    category: 'Solar & Renewable Energy',
    question: 'What is the main limitation of wind and solar renewable energy systems?',
    options: ['High carbon emissions', 'Intermittency and grid variability', 'Toxic exhaust gas', 'Depletion of solar radiation'],
    correctIndex: 1,
    explanation: 'Intermittency (nighttime, cloudy days, calm winds) requires grid balancing and energy storage.',
  },

  // 11-20: Water Resources & Hydrology
  {
    id: 'mcq-11',
    category: 'Water Resources',
    question: 'Excessive extraction of groundwater in coastal plains most commonly triggers:',
    options: ['Artesian spring emergence', 'Seawater intrusion into freshwater aquifers', 'Elevation of the piezometric head', 'Decrease in soil electrical conductivity'],
    correctIndex: 1,
    explanation: 'Lowering the hydraulic head allows denser marine saltwater to infiltrate coastal freshwater drinking wells.',
  },
  {
    id: 'mcq-12',
    category: 'Water Resources',
    question: 'Land subsidence due to groundwater pumping is caused by:',
    options: ['Thermal contraction of bedrock', 'Compaction and dewatering of fine-grained clay aquitards', 'Tectonic plate subduction', 'Dissolution of granite stones'],
    correctIndex: 1,
    explanation: 'As pore-water pressure decreases, sediment grains carry the overburden weight and compact irreversibly.',
  },
  {
    id: 'mcq-13',
    category: 'Water Resources',
    question: 'Which method is considered most water-efficient for agricultural crop irrigation?',
    options: ['Flood irrigation', 'Furrow irrigation', 'Drip / micro-irrigation', 'Wild flooding'],
    correctIndex: 2,
    explanation: 'Drip irrigation delivers water directly to plant root zones with efficiency rates exceeding 90%.',
  },
  {
    id: 'mcq-14',
    category: 'Water Resources',
    question: 'Artificial recharge wells serve to:',
    options: ['Extract deep fossil brine', 'Direct surplus surface rainwater directly into depleted aquifers', 'Pump toxic industrial waste underground', 'Monitor barometric pressure'],
    correctIndex: 1,
    explanation: 'Recharge wells channel clean collected surface runoff down into underlying aquifer formations.',
  },
  {
    id: 'mcq-15',
    category: 'Water Resources',
    question: 'What percentage of Earth\'s total water supply is readily accessible freshwater?',
    options: ['~25%', '~10%', 'Less than 1%', '~50%'],
    correctIndex: 2,
    explanation: 'Over 97% is ocean saltwater, ~2% is frozen in polar glaciers, leaving <1% as accessible liquid freshwater.',
  },
  {
    id: 'mcq-16',
    category: 'Water Resources',
    question: 'The boundary separating the unsaturated vadose zone from the saturated phreatic zone is the:',
    options: ['Water table', 'Aquitard', 'Perched aquifer', 'Capillary fringe summit'],
    correctIndex: 0,
    explanation: 'The water table marks where pore water pressure equals atmospheric pressure.',
  },
  {
    id: 'mcq-17',
    category: 'Water Resources',
    question: 'Water logging in heavily irrigated command areas frequently produces:',
    options: ['Soil acidification', 'Soil salinization and alkalinization', 'Rapid root aeration', 'Thermal decomposition'],
    correctIndex: 1,
    explanation: 'Evaporation of rising saline groundwater deposits mineral salts at the root zone.',
  },
  {
    id: 'mcq-18',
    category: 'Water Resources',
    question: 'Which parameter indicates organic pollution and oxygen depletion in a water body?',
    options: ['Biochemical Oxygen Demand (BOD)', 'Hardness ratio', 'Turbidity index', 'Total dissolved sulfur'],
    correctIndex: 0,
    explanation: 'High BOD indicates that microbes require substantial dissolved oxygen to decompose organic matter.',
  },
  {
    id: 'mcq-19',
    category: 'Water Resources',
    question: 'A watershed management approach aims primarily at:',
    options: ['Channeling all water to the ocean as fast as possible', 'Integrated conservation of land, water, and biomass in a river drainage basin', 'Diverting rivers exclusively to industrial plants', 'Draining wetlands for urban housing'],
    correctIndex: 1,
    explanation: 'Watershed development treats the geographical drainage basin as a unified ecological system.',
  },
  {
    id: 'mcq-20',
    category: 'Water Resources',
    question: 'Rainwater harvesting in semi-arid zones provides:',
    options: ['Immediate drought mitigation and aquifer replenishment', 'Increased soil erosion', 'Higher flood peaks', 'Loss of agricultural topsoil'],
    correctIndex: 0,
    explanation: 'Harvesting traps intermittent storm runoff to recharge aquifers and buffer against drought.',
  },

  // 21-30: Case Studies (Cauvery, Sardar Sarovar, Chipko)
  {
    id: 'mcq-21',
    category: 'Case Studies',
    question: 'The Sardar Sarovar Dam is constructed on which major river in western India?',
    options: ['Cauvery River', 'Narmada River', 'Tapi River', 'Godavari River'],
    correctIndex: 1,
    explanation: 'The Sardar Sarovar Dam is a major gravity dam built across the Narmada River in Gujarat.',
  },
  {
    id: 'mcq-22',
    category: 'Case Studies',
    question: 'The primary disputing states in the Cauvery River water dispute are:',
    options: ['Punjab and Haryana', 'Karnataka and Tamil Nadu', 'Maharashtra and Gujarat', 'Andhra Pradesh and Odisha'],
    correctIndex: 1,
    explanation: 'The principal contention exists between upper-riparian Karnataka and lower-riparian Tamil Nadu.',
  },
  {
    id: 'mcq-23',
    category: 'Case Studies',
    question: 'Who emerged as the prominent leader of the Narmada Bachao Andolan (NBA)?',
    options: ['Sunderlal Bahuguna', 'Medha Patkar', 'Chandi Prasad Bhatt', 'Vandana Shiva'],
    correctIndex: 1,
    explanation: 'Medha Patkar spearheaded the social and ecological movement against large dam displacements on the Narmada.',
  },
  {
    id: 'mcq-24',
    category: 'Case Studies',
    question: 'The historic Chipko movement originated in which Indian region during the 1970s?',
    options: ['Garhwal Himalayas (Uttarakhand)', 'Western Ghats (Kerala)', 'Thar Desert (Rajasthan)', 'Sundarbans (West Bengal)'],
    correctIndex: 0,
    explanation: 'Villagers in Reni village in the Chamoli district of Uttarakhand hugged trees to prevent commercial logging.',
  },
  {
    id: 'mcq-25',
    category: 'Case Studies',
    question: 'Which dam serves as the primary reservoir for the Cauvery delta in Tamil Nadu?',
    options: ['KRS (Krishna Raja Sagara) Dam', 'Mettur Dam (Stanley Reservoir)', 'Bhakra Nangal Dam', 'Hirakud Dam'],
    correctIndex: 1,
    explanation: 'Mettur Dam in Salem district, Tamil Nadu, regulates irrigation for the Cauvery agricultural delta.',
  },
  {
    id: 'mcq-26',
    category: 'Case Studies',
    question: 'Which dam on the Cauvery is situated in Karnataka near Mysore?',
    options: ['Krishna Raja Sagara (KRS) Dam', 'Idukki Dam', 'Tehri Dam', 'Koyna Dam'],
    correctIndex: 0,
    explanation: 'KRS Dam across the Cauvery River is situated in Mandya/Mysore district, Karnataka.',
  },
  {
    id: 'mcq-27',
    category: 'Case Studies',
    question: 'The Silent Valley Movement succeeded in saving which type of ecosystem in Kerala?',
    options: ['Mangrove swamp', 'Tropical evergreen rainforest', 'Alpine tundra', 'Thorny scrubland'],
    correctIndex: 1,
    explanation: 'The protest saved 8.3 sq km of pristine tropical evergreen rainforest from hydroelectric flooding.',
  },
  {
    id: 'mcq-28',
    category: 'Case Studies',
    question: 'The Supreme Court of India in the Cauvery water dispute affirmed that waters of an inter-state river are:',
    options: ['Exclusive property of the upper-riparian state', 'A national asset in which no state can claim proprietary rights', 'Sole property of the lower-riparian state', 'Sole property of private agricultural companies'],
    correctIndex: 1,
    explanation: 'The Supreme Court ruled that inter-state rivers are national assets shared equitably among riparian states.',
  },
  {
    id: 'mcq-29',
    category: 'Case Studies',
    question: 'Gaura Devi is celebrated in Indian environmental history for her role in:',
    options: ['Chipko Movement tree-hugging protest', 'Developing fuel cell membranes', 'Constructing solar thermal plants', 'Drilling deep tube wells'],
    correctIndex: 0,
    explanation: 'Gaura Devi led 27 local women in Reni village who confronted commercial loggers by hugging trees in 1974.',
  },
  {
    id: 'mcq-30',
    category: 'Case Studies',
    question: 'The Tehri Dam on the Bhagirathi River faced major protests primarily due to:',
    options: ['Lack of concrete', 'High seismic vulnerability in the Himalayan thrust zone', 'Low water storage', 'High water temperature'],
    correctIndex: 1,
    explanation: 'Geologists and activists raised alarm regarding severe earthquake hazards in the Himalayan seismic gap.',
  },

  // 31-40: Fuel Cells & Electrochemical Thermodynamics
  {
    id: 'mcq-31',
    category: 'Fuel Cells',
    question: 'Which electrolyte is utilized in Proton Exchange Membrane (PEM) fuel cells?',
    options: [
      'Aqueous Potassium Hydroxide (KOH)',
      'Solid polymer membrane (fluorinated sulfonic acid like Nafion)',
      'Molten Carbonate salt mixture',
      'Concentrated Phosphoric acid',
    ],
    correctIndex: 1,
    explanation: 'PEM fuel cells use a perfluorosulfonic acid polymer membrane that conducts protons while remaining an electrical insulator.',
  },
  {
    id: 'mcq-32',
    category: 'Fuel Cells',
    question: 'The theoretical maximum thermodynamic efficiency of a hydrogen-oxygen fuel cell at 25°C is:',
    options: ['40%', '65%', '83%', '100%'],
    correctIndex: 2,
    explanation: 'Efficiency = (ΔG / ΔH) * 100 = (56.65 / 68.26) * 100 = 83.0%.',
  },
  {
    id: 'mcq-33',
    category: 'Fuel Cells',
    question: 'Solid Oxide Fuel Cells (SOFC) operate at approximately which temperature range?',
    options: ['60°C to 80°C', '150°C to 200°C', '600°C to 1000°C', '2500°C to 3000°C'],
    correctIndex: 2,
    explanation: 'SOFCs use ceramic electrolytes (YSZ) requiring 600°C to 1000°C to achieve adequate oxygen ion conductivity.',
  },
  {
    id: 'mcq-34',
    category: 'Fuel Cells',
    question: 'The sole direct chemical emission of a pure hydrogen fuel cell is:',
    options: ['Carbon Monoxide', 'Pure Water (H2O) and Heat', 'Nitrogen Oxides (NOx)', 'Sulfur Dioxide (SO2)'],
    correctIndex: 1,
    explanation: 'Combining 2H2 + O2 yields only liquid/vapor H2O and thermal energy.',
  },
  {
    id: 'mcq-35',
    category: 'Fuel Cells',
    question: 'Catalyst poisoning in low-temperature PEM fuel cells is most severely caused by traces of:',
    options: ['Nitrogen gas (N2)', 'Carbon Monoxide (CO)', 'Water vapor (H2O)', 'Argon (Ar)'],
    correctIndex: 1,
    explanation: 'CO binds aggressively to platinum catalyst active sites, blocking hydrogen gas dissociation.',
  },
  {
    id: 'mcq-36',
    category: 'Fuel Cells',
    question: 'Fuel cells are exempt from the Carnot thermodynamic efficiency limitation because:',
    options: ['They operate at cryogenic temperatures', 'They convert chemical free energy directly into electrical energy', 'They do not generate heat', 'They use infinite pressure'],
    correctIndex: 1,
    explanation: 'Carnot limits apply strictly to heat engines converting thermal energy to mechanical work.',
  },
  {
    id: 'mcq-37',
    category: 'Fuel Cells',
    question: 'In a PEM fuel cell, which charge carrier migrates across the polymer electrolyte membrane?',
    options: ['Electrons (e-)', 'Protons (H+)', 'Oxide ions (O2-)', 'Hydroxide ions (OH-)'],
    correctIndex: 1,
    explanation: 'Protons (H+) pass through the hydrated sulfonic acid channels of the membrane to the cathode.',
  },
  {
    id: 'mcq-38',
    category: 'Fuel Cells',
    question: 'The steep voltage drop at very low current density on a fuel cell polarization curve is caused by:',
    options: ['Activation polarization / charge transfer resistance', 'Ohmic resistance of wires', 'Mass transport flooding', 'Membrane puncture'],
    correctIndex: 0,
    explanation: 'Activation overpotential is the energy barrier required to initiate electrochemical charge transfer.',
  },
  {
    id: 'mcq-39',
    category: 'Fuel Cells',
    question: 'Green hydrogen is synthesized primarily through:',
    options: ['Coal gasification with no carbon capture', 'Electrolysis of water powered by renewable solar/wind power', 'Steam methane reforming of natural gas', 'Partial oxidation of heavy crude oil'],
    correctIndex: 1,
    explanation: 'Green hydrogen uses zero-emission renewable electricity to split water into H2 and O2.',
  },
  {
    id: 'mcq-40',
    category: 'Fuel Cells',
    question: 'Alkaline fuel cells (AFC) utilize which liquid electrolyte?',
    options: ['Potassium hydroxide (KOH) solution', 'Sulfuric acid (H2SO4)', 'Hydrochloric acid (HCl)', 'Liquid ammonia'],
    correctIndex: 0,
    explanation: 'AFCs use aqueous KOH solution, operating efficiently at 60–90°C.',
  },

  // 41-50: Land Resources & Environmental Policy
  {
    id: 'mcq-41',
    category: 'Land & Environmental Policy',
    question: 'Contour farming and terracing are primarily practiced on steep terrains to prevent:',
    options: ['Water stagnation', 'Soil erosion and gully formation', 'Insect infestation', 'Excessive sunlight'],
    correctIndex: 1,
    explanation: 'Terraces and contour bunds break downhill water velocity, retaining topsoil and moisture.',
  },
  {
    id: 'mcq-42',
    category: 'Land & Environmental Policy',
    question: 'The Forest Conservation Act in India was enacted in which year?',
    options: ['1972', '1980', '1992', '2005'],
    correctIndex: 1,
    explanation: 'The Forest (Conservation) Act was enacted in 1980 to control ongoing deforestation.',
  },
  {
    id: 'mcq-43',
    category: 'Land & Environmental Policy',
    question: 'Linear strips of trees planted across wind directions to halt soil drift in arid zones are called:',
    options: ['Check dams', 'Shelterbelts / windbreaks', 'Percolation tanks', 'Riparian buffers'],
    correctIndex: 1,
    explanation: 'Shelterbelts reduce wind speed at the ground surface, protecting loose dry topsoil.',
  },
  {
    id: 'mcq-44',
    category: 'Land & Environmental Policy',
    question: 'Eutrophication in lakes and slow-moving rivers is triggered by runoff rich in:',
    options: ['Calcium and magnesium', 'Nitrogen and phosphorus fertilizers', 'Inert sand particles', 'Dissolved oxygen'],
    correctIndex: 1,
    explanation: 'Excessive agricultural nitrogen and phosphorus stimulate suffocating algal blooms.',
  },
  {
    id: 'mcq-45',
    category: 'Land & Environmental Policy',
    question: 'The Ramsar Convention is an international environmental treaty focused on:',
    options: ['Ozone layer preservation', 'Conservation and sustainable use of wetlands', 'Transboundary hazardous waste trade', 'Space satellite debris'],
    correctIndex: 1,
    explanation: 'Signed in Ramsar, Iran in 1971, the treaty protects wetlands of international importance.',
  },
  {
    id: 'mcq-46',
    category: 'Land & Environmental Policy',
    question: 'The Environment (Protection) Act in India was passed in 1986 following which disaster?',
    options: ['Chernobyl disaster', 'Bhopal Gas Tragedy', 'Fukushima disaster', 'Exxon Valdez oil spill'],
    correctIndex: 1,
    explanation: 'The 1984 Bhopal gas tragedy prompted India to pass the comprehensive Environment Protection Act of 1986.',
  },
  {
    id: 'mcq-47',
    category: 'Land & Environmental Policy',
    question: 'Which method integrates forestry trees with agricultural crops on the same parcel of land?',
    options: ['Monoculture', 'Agroforestry', 'Slash-and-burn shifting cultivation', 'Clear-cutting'],
    correctIndex: 1,
    explanation: 'Agroforestry combines agriculture and forestry to optimize soil fertility and biodiversity.',
  },
  {
    id: 'mcq-48',
    category: 'Land & Environmental Policy',
    question: 'Desertification vulnerability is highest in which climatic zone?',
    options: ['Tropical rainforests', 'Arid and semi-arid drylands', 'Polar tundra', 'Alpine summits'],
    correctIndex: 1,
    explanation: 'Drylands have fragile topsoil vulnerable to overgrazing, drought, and climate swings.',
  },
  {
    id: 'mcq-49',
    category: 'Land & Environmental Policy',
    question: 'The principle that the polluter should bear the expenses of carrying out pollution prevention is:',
    options: ['Public Trust Doctrine', 'Polluter Pays Principle', 'Precautionary Principle', 'Equitable Utilization Rule'],
    correctIndex: 1,
    explanation: 'The Polluter Pays Principle mandates that polluting parties pay for environmental remediation.',
  },
  {
    id: 'mcq-50',
    category: 'Land & Environmental Policy',
    question: 'Under the National Action Plan on Climate Change (NAPCC), how many dedicated missions exist?',
    options: ['4 missions', '8 missions', '12 missions', '16 missions'],
    correctIndex: 1,
    explanation: 'India\'s NAPCC encompasses 8 national missions addressing solar, water, agriculture, and habitats.',
  },
];
